'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
let W=1100,H=620,time=0,camera=0,index=0,level=LEVELS[0],mode='intro',objects=[],platforms=[],stars=[],particles=[],flags={},collected=0,lowGravity=false,ballast=false,sound=false,audio=null,hintStep=0,seq=[0,0],last=0;
const keys={left:false,right:false,up:false,down:false};let jumpQueued=false;
const player={x:100,y:G,vx:0,vy:0,onGround:true,face:1,support:null,drop:0};
let finished=[];try{finished=JSON.parse(localStorage.getItem('milo-atlas-v3')||'[]')}catch{}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const near=(a,b,r)=>Math.abs(a-b)<r;
function resize(){W=clamp(canvas.parentElement.clientWidth,720,1250);canvas.width=W;canvas.height=H;canvas.style.aspectRatio=W+'/'+H}resize();window.addEventListener('resize',resize);
function tone(f,d=.16){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function clearKeys(){Object.keys(keys).forEach(k=>keys[k]=false);jumpQueued=false}
function reset(){clearKeys();flags={};collected=0;seq=[0,0];lowGravity=false;ballast=false;hintStep=0;time=0;camera=0;particles=[];Object.assign(player,{x:100,y:G,vx:0,vy:0,onGround:true,face:1,support:null,drop:0});objects=level.objects.map(o=>({...o,on:false,timer:0,angle:o.kind==='mirror'?(o.correct+1)%3:2,progress:0,py:G,previousY:G,px:o.x,metalX:o.metal,boxX:o.box}));stars=level.stars.map(([x,y,need],i)=>({x,y,need,i,got:false}));refreshPlatforms(0);$('hint').textContent=level.question;sync()}
function loadLevel(i){index=i;level=LEVELS[i];const c=themes[level.theme];document.documentElement.style.setProperty('--bg',c[4]);document.documentElement.style.setProperty('--accent',c[2]);$('chapter').textContent='CHAPITRE '+String(i+1).padStart(2,'0')+' / 15 · '+level.stars.length+' ÉTOILES';$('levelName').textContent=level.name;$('concept').textContent=level.concept;reset();show('intro',level.name,level.question,'Entrer dans ce monde →');buildMap()}
function sync(){$('count').textContent='✦ '+collected+' / '+stars.length;$('progress').style.width=(100*collected/stars.length)+'%';$('region').textContent=level.underwater?(ballast?'Lest : lourd ↓':'Lest : léger ↑'):level.theme==='moon'?(lowGravity?'Gravité : faible':'Gravité : forte'):'EXPLORATION LIBRE'}
function show(state,title,msg,button){mode=state;clearKeys();$('title').textContent=title;$('message').textContent=msg;$('play').textContent=button;$('overline').textContent=state==='won'?'UNE DÉCOUVERTE DE PLUS':state==='paused'?'LE MONDE PEUT ATTENDRE':'UNE NOUVELLE EXPÉDITION';$('overlay').hidden=false;$('prompt').hidden=true}
function play(){if(mode==='won'){loadLevel((index+1)%15);return}mode='playing';$('overlay').hidden=true;canvas.focus()}
function pause(){if(mode==='playing')show('paused','Une petite respiration.', 'Ton exploration est conservée. Reviens quand tu veux.','Reprendre →');else if(mode==='paused')play()}
function buildMap(){$('levelCards').innerHTML=LEVELS.map((l,i)=>{const c=themes[l.theme];return '<button class="levelcard" data-level="'+i+'" style="--sky:'+c[0]+';--land:'+c[1]+';--light:'+c[2]+'"><div class="mini" data-symbol="'+l.symbol+'"></div><span class="label"><em>'+String(i+1).padStart(2,'0')+(finished.includes(i)?' · EXPLORÉ ✓':' · '+l.stars.length+' ÉTOILES')+'</em><b>'+l.name+'</b><small>'+l.concept+'</small></span></button>'}).join('');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{$('atlas').close();loadLevel(+b.dataset.level)})}
function nearest(){return objects.filter(o=>!['moving','reef','stop','weight'].includes(o.kind)&&near(o.x,player.x,85)&&near(o.y,player.y,115)).sort((a,b)=>Math.abs(a.x-player.x)-Math.abs(b.x-player.x))[0]}
function act(){if(mode!=='playing')return;if(level.underwater){ballast=!ballast;$('hint').textContent=ballast?'Le lest augmente ton poids : observe la descente.':'Le lest est allégé : observe la remontée.';sync();return}const o=nearest();if(!o){$('hint').textContent='Approche-toi d’un objet marqué E pour agir.';return}
if(o.kind==='water'){o.on=true;flags[o.id]=true;$('hint').textContent='La plante grandit ! Ses feuilles deviennent des appuis.'}
if(o.kind==='fan'){if(o.requires&&!o.requires.every(f=>flags[f])){$('hint').textContent='Il manque une source : allume le cristal et livre le noyau sur le tapis.';return}o.on=!o.on;flags[o.id]=o.on;$('hint').textContent=o.on?'Entre dans le courant : le vent te soulève.':'Le courant est arrêté.'}
if(o.kind==='tide'){o.on=!o.on;flags[o.id]=o.on;$('hint').textContent=o.on?'L’écluse monte : observe le bateau.':'L’eau redescend avec le bateau.'}
if(o.kind==='magnet'){o.on=!o.on;$('hint').textContent=o.on?'L’aimant attire le fer. Observe le bloc sur le rail.':'L’aimant est arrêté.'}
if(o.kind==='gravity'){lowGravity=!lowGravity;$('hint').textContent=lowGravity?'Gravité faible : compare ton prochain saut.':'Gravité forte : compare ton prochain saut.';sync()}
if(o.kind==='mirror'){o.angle=(o.angle+1)%3;flags[o.id]=o.angle===o.correct;$('hint').textContent=flags[o.id]?'Le rayon atteint le cristal : les marches apparaissent !':'Le rayon manque le cristal. Essaie une autre orientation.'}
if(o.kind==='belt'){o.dir*=-1;$('hint').textContent='Le tapis transporte maintenant le colis vers '+(o.dir>0?'la droite.':'la gauche.')}
if(o.kind==='bell'){const group=o.group||0;if(o.note===seq[group]){seq[group]++;if(seq[group]===3){flags['song'+group]=true;$('hint').textContent='La mélodie est complète : le coffre s’ouvre !'}else $('hint').textContent='Bien ! '+seq[group]+' / 3 notes. Cherche le symbole suivant.'}else{seq[group]=o.note===0?1:0;$('hint').textContent='Écoute encore : ♧ puis ☾ puis ☀. Tu peux réessayer.'}tone([440,550,660][o.note],.5)}
if(o.kind==='portal'){flags[o.id]=true;burst(o.x,o.y-50);Object.assign(player,{x:o.to[0],y:o.to[1],vx:0,vy:0,onGround:true,support:null});camera=clamp(player.x-W*.4,0,level.width-W);burst(player.x,player.y-50);$('hint').textContent='Même symbole, autre endroit. Explore cette île avant de revenir.'}
if(o.kind==='spring'&&o.adjust){o.power=o.power===690?970:690;$('hint').textContent='Rebond '+(o.power===970?'fort ↑':'doux')+'. Essaie et compare.'}
tone(520);canvas.focus()}
function burst(x,y){for(let i=0;i<20;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.6)*180,life:1})}
function refreshPlatforms(dt){platforms=[];for(const p of level.platforms){if(p.need&&!flags[p.need])continue;if(p.grow){const o=objects.find(o=>o.id===p.grow);o.progress=clamp(o.progress+(o.on?dt*.8:0),0,1);if(o.progress<.01)continue;const y=G+(p.y-G)*o.progress;platforms.push({...p,y}); // Intermediate leaves make every plant climbable.
platforms.push(P(p.x-105,G-90*o.progress,130));if(p.y<320)platforms.push(P(p.x-30,G-175*o.progress,110));}else platforms.push({...p})}
for(const o of objects){o.previousY=o.py;if(o.kind==='moving'){o.py=o.top+Math.cos(time*2*Math.PI/o.period)*o.range/2;platforms.push(P(o.x,o.py,o.w,{obj:o}))}
if(o.kind==='tide'){o.py+=clamp((o.on?290:G-12)-o.py,-55*dt,55*dt);platforms.push(P(o.zone+30,o.py,o.w-60,{obj:o}))}
if(o.kind==='weight'){flags[o.id]=near(o.boxX+32,o.x,44);o.py+=clamp((flags[o.id]?290:G)-o.py,-45*dt,45*dt);platforms.push(P(o.lift-130,425,140));platforms.push(P(o.lift,o.py,160,{obj:o}));platforms.push(P(o.boxX,G-68,64,{box:o}))}
if(o.kind==='belt')platforms.push(P(o.zone,G-15,o.w,{belt:o}));
if(o.kind==='spring')platforms.push(P(o.x,G-15,130,{spring:o}));}
}
function update(dt){if(mode!=='playing'){jumpQueued=false;return}time+=dt;const prevSupport=player.support;refreshPlatforms(dt);if(prevSupport&&player.onGround){const o=prevSupport.obj;if(o)player.y+=o.py-o.previousY;const belt=prevSupport.belt;if(belt)player.x+=belt.dir*80*dt}
const axis=Number(keys.right)-Number(keys.left);let target=axis*(level.underwater?190:245);const accel=level.ice?330:level.underwater?700:2200;
if(axis)player.vx+=clamp(target-player.vx,-accel*dt,accel*dt);else player.vx*=Math.exp(-(level.ice?.5:level.underwater?2.6:16)*dt);
if(Math.abs(player.vx)>12)player.face=Math.sign(player.vx);
if(jumpQueued&&player.onGround&&!level.underwater){player.vy=-580;player.onGround=false;tone(290,.08)}jumpQueued=false;
let gravity=lowGravity?520:1150;if(level.underwater){gravity=ballast?170:-160;if(keys.up)gravity-=420;if(keys.down)gravity+=420;player.vy*=Math.exp(-1.8*dt)}
for(const o of objects){if(o.kind==='fan'&&o.on&&player.x>o.zone&&player.x<o.zone+o.w&&player.y>105){gravity-=1750;player.vy=Math.max(-260,player.vy)}
if(o.kind==='stop'){if(near(player.x,o.x,40)&&Math.abs(player.vx)<25&&player.onGround)o.timer+=dt;else o.timer=0;if(o.timer>1.1)flags[o.id]=true}
if(o.kind==='magnet'&&o.on){o.metalX+=(o.target-o.metalX)*Math.min(1,dt*.9);if(near(o.metalX,o.target,10))flags[o.id]=true}
if(o.kind==='belt'){o.boxX=clamp(o.boxX+o.dir*65*dt,o.zone+8,o.zone+o.w-35);if(near(o.boxX,o.target,24))flags[o.id]=true}}
let nx=clamp(player.x+player.vx*dt,35,level.width-35);for(const o of objects)if(o.kind==='weight'&&player.y>G-64&&nx+13>o.boxX&&nx-13<o.boxX+64){const dx=nx-player.x;o.boxX=clamp(o.boxX+dx*.7,45,level.width-100);nx=dx>0?o.boxX-13:dx<0?o.boxX+77:player.x}
player.x=nx;player.drop=Math.max(0,(player.drop||0)-dt);if(keys.down&&player.onGround&&player.support&&!level.underwater){player.drop=.35;player.y+=6;player.onGround=false}const oldY=player.y;player.vy=clamp(player.vy+gravity*dt,-950,800);player.y+=player.vy*dt;player.onGround=false;player.support=null;
if(player.vy>=0){let floor=G,support=null;for(const p of platforms)if(!player.drop&&player.x+12>p.x&&player.x-12<p.x+p.w&&oldY<=p.y+4&&player.y>=p.y&&p.y<=floor){floor=p.y;support=p}if(player.y>=floor){player.y=floor;if(support?.spring){player.vy=-support.spring.power;burst(player.x,player.y);tone(360,.15)}else{player.vy=0;player.onGround=true;player.support=support}}}
if(player.y<105){player.y=105;player.vy=Math.max(0,player.vy)}
for(const s of stars)if(!s.got&&(!s.need||flags[s.need])&&near(player.x,s.x,34)&&s.y>player.y-91&&s.y<player.y+7){s.got=true;collected++;burst(s.x,s.y);tone(470+collected*70);sync();if(collected===stars.length){if(!finished.includes(index)){finished.push(index);try{localStorage.setItem('milo-atlas-v3',JSON.stringify(finished))}catch{}}show('won','Le monde s’illumine.',level.fact,index===14?'Revenir à la forêt →':'Découvrir le monde suivant →');buildMap()}}
for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=80*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);
camera+=(clamp(player.x-W*.37,0,level.width-W)-camera)*Math.min(1,dt*5);const o=nearest();$('prompt').hidden=level.underwater?false:!o;if(level.underwater)$('prompt').textContent='E · '+(ballast?'Retirer le lest ↑':'Ajouter du lest ↓');else if(o)$('prompt').textContent='E · '+({water:'Arroser',fan:'Actionner le moulin',tide:'Ouvrir / fermer l’écluse',magnet:'Activer / arrêter l’aimant',gravity:'Changer la gravité',mirror:'Tourner le miroir',belt:'Inverser le tapis',bell:'Jouer '+o.label,portal:'Traverser '+o.label,spring:'Régler le rebond'}[o.kind]||'Observer');}
$('play').onclick=play;$('pause').onclick=pause;$('retry').onclick=()=>{reset();play()};$('clue').onclick=()=>{$('hint').textContent=level.hint;canvas.focus()};$('actTouch').onclick=act;$('sound').onclick=()=>{sound=!sound;$('sound').textContent='Son : '+(sound?'oui':'non');tone(440);canvas.focus()};$('mapButton').onclick=()=>{if(mode==='playing')pause();buildMap();$('atlas').showModal()};$('closeMap').onclick=()=>$('atlas').close();
function input(e,down){if($('atlas').open)return;const map={ArrowLeft:'left',KeyA:'left',KeyQ:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',KeyZ:'up',Space:'up',ArrowDown:'down',KeyS:'down'};if(map[e.code]){if(e.target.tagName==='BUTTON'&&down)return;e.preventDefault();keys[map[e.code]]=down;if(down&&!e.repeat&&map[e.code]==='up')jumpQueued=true}if(down&&!e.repeat&&e.code==='KeyE'){e.preventDefault();act()}if(down&&!e.repeat&&e.code==='KeyP')pause()}
window.addEventListener('keydown',e=>input(e,true));window.addEventListener('keyup',e=>input(e,false));window.addEventListener('blur',()=>{clearKeys();if(mode==='playing')pause()});document.querySelectorAll('[data-key]').forEach(b=>{const key=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(key==='jump'){jumpQueued=true;keys.up=true}else keys[key]=true});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{if(key==='jump')keys.up=false;else keys[key]=false})});
